Load required packages
```{r}
library(tidyverse)
library(ggmap)
library(ggthemes)
library(leaflet)
library(openintro)
library(sf)
```


Read Starbucks data
```{r}
starbucks <- read_csv("https://bcheggeseth.github.io/112_spring_2023/data/starbucks.csv")
glimpse(starbucks)
```

Starbucks stores in US only
```{r}
starbucks_us <- starbucks %>% filter(Country == "US")
glimpse(starbucks_us)
```
# Visualize Stores as Individual Points

## Scatter plot
```{r}
ggplot(data = starbucks_us, mapping = aes(x = Longitude, y = Latitude)) +
  geom_point()
```

## Scatter plot + map underneath
```{r}
# get a map of the world
map_us <- get_stamenmap(
  bbox = c(left = -132, bottom = 20, right = -65, top = 55),
  maptype = "terrain",
  zoom = 5
)


# show the map beneath the scatter plot
ggmap(ggmap = map_us) +
  geom_point(data = starbucks_us, 
             mapping = aes(x = Longitude, y = Latitude))
```

## interactive map
Only a sample of 10 stores
```{r}
leaflet(data = sample_n(starbucks_us, 10)) %>% 
  addTiles() %>% 
  addMarkers()
```

# As s summary

## Contour
```{r}
ggmap(ggmap = map_us) +
  stat_density_2d(data = starbucks_us, mapping = aes(x = Longitude, y = Latitude))
```

## Contour with colored slices (not good)
```{r}
ggmap(ggmap = map_us) +
  stat_density_2d_filled(
    data = starbucks_us, 
    mapping = aes(x = Longitude, y = Latitude),
    alpha = .3,
    bins = 5)
```

## Contour with colored slices
```{r}
ggmap(ggmap = map_us) +
  stat_density_2d(data = starbucks_us, 
                  mapping = aes(x = Longitude, y = Latitude, fill = after_stat(level)), 
                  geom = "polygon",
                  alpha = .3,
                  color = "black",
                  bins = 5) +
  scale_fill_gradient(low = "darkblue", high = "red", guide = "none")
```

## choropleth map
```{r}
# compute number of stores in each state
# add full state names
starbucks_us_states <- starbucks_us %>% 
  count(`State/Province`) %>% 
  mutate(state_name = str_to_lower(abbr2state(`State/Province`)))

map_us_polygons <- map_data("state")

ggplot(data = starbucks_us_states) + 
  geom_map(map = map_us_polygons, mapping = aes(map_id = state_name, fill = n)) +
  expand_limits(x = map_us_polygons$long, y = map_us_polygons$lat)
```


## interactive map
```{r}
map_us_json <- geojsonio::geojson_read("https://rstudio.github.io/leaflet/json/us-states.geojson", what = "sp")

leaflet(data = map_us_json) %>% 
  addTiles() %>% 
  addPolygons()
```

